default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  primary:
    <<: *default
    database: print_queue_development
  cable:
    <<: *default
    database: print_queue_development_cable
    migrations_paths: db/cable_migrate
  queue:
    <<: *default
    database: print_queue_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: print_queue_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: 5
  cable:
    <<: *primary_production
    database: app_production_cable
    migrations_paths: db/cable_migrate
  queue:
    <<: *primary_production
    url: <%= ENV["SOLID_QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths: db/cache_migrate