development:
  etsy_sync:
    class: EtsySyncJob
    schedule: "every minute"  # Every Minute for development testing
    queue: default

production:
  etsy_sync:
    class: EtsySyncJob
    schedule: "0,30 * * * *"  # At minute 0 and 30 of every hour
    queue: default